version: 2

jobs:
  tests:
    docker:
      - image: macrometa/c8automation
        auth:
          username: $MACROMETA_DOCKERHUB_USERNAME
          password: $MACROMETA_DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Installing packages
          command : sudo pip3 install -r functional/requirements.txt
          when: always
      - run:
          name: Check pep8 errors
          command: pycodestyle run_workflows.py functional/ diagnostics/
      - run:
          name: Cleaningup resources from previous run
          command: url=$(cat ./functional_workflows.yaml | grep -v "#" | grep url) && fed_url=$(echo $url | cut -d" " -f2) && if [[ $fed_url != "default.dev.aws.macrometa.io" ]]; then python3 functional/cleanup.py ${fed_url} ; fi
          when: always
      - run:
          name: Run tests
          command: python3 run_workflows.py
      - run:
          name: Cleanup resources
          command: url=$(cat ./functional_workflows.yaml | grep -v "#" | grep url) && fed_url=$(echo $url | cut -d" " -f2) && if [[ $fed_url != "default.dev.aws.macrometa.io" ]]; then python3 functional/cleanup.py ${fed_url} ; fi
          when: always
      - run:
          name: Listing Pod Crashes 
          command: url=$(cat ./functional_workflows.yaml | grep -v "#" | grep url) && fed_url=$(echo $url | cut -d" " -f2) && if [[ $fed_url != "default.dev.aws.macrometa.io" ]]; then python3 functional/podcrash.py ${fed_url}; fi
          when: always
workflows:
  version: 2
  primary:
    jobs:
      - tests
